Shopweb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/",include('account.urls',namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove_item/', views.remove_item, name='remove_item'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('verify-code/', views.verify_code, name='verify_code'),
    path('create-order/', views.create_order, name='create_order'),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_details/<int:id>', views.order_detail, name='order_detail'),
    path('pdf/<int:id>>', views.send_to_pdf, name='pdf'),
    path('reference/<int:id>', views.reference, name='reference'),
    path('apply-discount/',views.apply_discount, name='apply_discount'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [

    path('product/', views.product_list, name='product_list'),
    path('product/<slug:category_slug>', views.product_list, name='product_by_category'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('product/save/<int:id>', views.save, name='save'),
    path('product/save_list/', views.save_list, name='save_list')
]

orders/models.py
from django.db import models
from shop.models import *
from account.models import *


# Create your models here.


class Order(models.Model):
    STATUS_CHOICES = [
        ('C0', 'Confirm'),
        ('Q1', 'In the review queue'),
        ('R2', 'Received from the seller'),
        ('P3', 'Preparing the order'),
        ('D4', 'Delivery to the post office'),
        ('D5', 'Delivery to the customer'),
        ('R6', 'Return of the cost due to lack of stock'),
        ('N7', 'Not Paid')
    ]

    buyer = models.ForeignKey(ShopUser, on_delete=models.SET_NULL, related_name='orders', null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=10)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status_order = models.CharField(max_length=2, choices=STATUS_CHOICES, default='In the review queue')

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_post_cost(self):
        weight = sum(item.get_weight() for item in self.items.all())
        if weight < 1000:
            return 20000
        elif 1000 <= weight <= 2000:
            return 30000
        else:
            return 50000

    def get_final_cost(self):
        price = self.get_post_cost() + self.get_total_cost()
        return price


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    weight = models.PositiveIntegerField(default=0)

    def get_cost(self):
        return self.price * self.quantity

    def get_weight(self):
        return self.quantity * self.weight


class DiscountCode(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

orders/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class PhoneVerificationForm(forms.Form):
    phone = forms.CharField(max_length=11)
    password = forms.CharField()


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order

        fields = ['first_name','last_name', 'phone','address','postal_code','province','city']

orders/views.py
from django.shortcuts import render, redirect
from .forms import *
from account.models import ShopUser
import random
from django.contrib import messages
from cart.common.sms import send_sms_with_template, send_sms_normal
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.http import HttpResponse,JsonResponse
import requests
import json
from django.conf import settings
from orders.models import *
import time
from django.contrib.auth import login, logout, authenticate
from django_xhtml2pdf.utils import generate_pdf
from django.template.loader import get_template
from io import BytesIO
from xhtml2pdf import pisa
from django.core.mail import BadHeaderError, send_mail
from shop.models import *
from django.utils import timezone


def verify_phone(request):
    if request.method == 'POST':
        form = PhoneVerificationForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            if ShopUser.objects.filter(phone=phone).exists():
                user = authenticate(request, username=phone,
                                    password=request.POST['password'])
                login(request, user)
                messages.error(request, 'this phone is already registered.')
                return redirect("orders:create_order")

            else:
                tokens = {'token': ''.join(random.choices('0123456789', k=4))}
                time1 = time.time()
                request.session['verification_code'] = tokens['token']
                request.session['phone'] = phone
                request.session['time1'] = time1
                request.session['password'] = request.POST.get('password')
                print(tokens)
                send_sms_normal()
                messages.error(request, 'verification code sent successfully.')
                return redirect('orders:verify_code', )
    elif request.user.is_authenticated:
        return redirect('orders:create_order')
    else:
        form = PhoneVerificationForm()
    return render(request, 'verify_phone.html', {'form': form})


def verify_code(request):
    if request.method == 'POST':
        time2 = time.time()
        time1 = request.session['time1']
        if time2 - time1 < 120:
            code = request.POST.get('code')
            verification_code = request.session['verification_code']
            phone = request.session['phone']
            if code == verification_code:
                user = ShopUser.objects.create_user(phone)
                user.set_password(request.session['password'])
                # muss send sms to user
                user.save()
                # print(user)
                login(request, user)
                del request.session['verification_code']
                del request.session['phone']

                return redirect('orders:create_order')

            else:
                messages.error(request, 'verification code is wrong')
        else:
            messages.error(request, 'The code has expired')
            return redirect('orders:verify_phone')
    return render(request, 'verify_code.html')


@login_required
def create_order(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderForm(request.POST)
        # form.first_name(initial='11')

        # form_name = OrderForm.first_name(initial=request.user)
        if form.is_valid:

            order = form.save()
            order.buyer = request.user
            order.save()

            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'],
                                         weight=item['weight'])
            cart.clear()
            request.session['order_id'] = order.id
            return redirect('orders:request')

    else:
        form = OrderForm()
    context = {
        'cart': cart,
        'form': form,
    }
    return render(request, 'create_order.html', context)


#
# if settings.SANDBOX:
#     sandbox = 'sandbox'
# else:
#     sandbox = 'www'

ZP_API_REQUEST = f"https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://sandbox.zarinpal.com/pg/StartPay/"

CallbackURL = 'http://127.0.0.1:8000/orders/verify/'


def send_request(request):
    order = Order.objects.get(id=request.session['order_id'])
    description = ""
    for item in order.items.all():
        description += item.product.name + ", "
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Description": description,
        "Phone": request.user.phone,
        "CallbackURL": CallbackURL,
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

        if response.status_code == 200:
            response_json = response.json()
            authority = response_json['Authority']
            if response_json['Status'] == 100:
                return redirect(ZP_API_STARTPAY + authority)
            else:
                return HttpResponse('Error')
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def verify(request):
    order = Order.objects.get(id=request.session['order_id'])
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Authority": request.GET.get('Authority'),
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_VERIFY, data=data, headers=headers)
        if response.status_code == 200:
            response_json = response.json()
            reference_id = response_json['RefID']

            if response_json['Status'] == 100:
                for item in order.items.all():
                    item.product.inventory -= item.quantity
                    item.product.save()
                order.paid = True
                order.save()
                return render(request, 'payment-tracking.html',
                              {"success": True, 'RefID': reference_id, "order_id": order.id})
            else:
                return render(request, 'payment-tracking.html',
                              {"success": False, })
        del request.session['order_id']
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def order_list(request):
    user = request.user
    order = Order.objects.filter(buyer=user)
    return render(request, 'order_list.html', {'order': order})


@login_required
def order_detail(request, id):
    user = request.user
    order = Order.objects.get(id=id)
    if user == order.buyer:
        show_status = list(map(lambda x: Order.STATUS_CHOICES[int(order.status_order[1])][1], Order.STATUS_CHOICES))
        context = {
            'order': order,
            'status': show_status[1],
        }
        return render(request, 'order_detail.html', context)
    else:
        return HttpResponse('This URL is not related to this user.')


def send_to_pdf(request, id):
    user = request.user
    order = Order.objects.get(id=id)
    if user == order.buyer:
        show_status = list(map(lambda x: Order.STATUS_CHOICES[int(order.status_order[1])][1], Order.STATUS_CHOICES))
        context_pdf = {
            'order': order,
            'status': show_status[1]

        }
        pdf = render_to_pdf('order_detail_pdf.html', context_pdf)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "order detail_%s.pdf" % order.first_name
            content = "inline; filename='%s'" % filename
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % filename
            response['Content-Disposition'] = content
            return response


def render_to_pdf(template_src, context_dict=None):
    if context_dict is None:
        raise ValueError("CSS file data is None. Please check the file path and content.")
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


def reference(request, id):
    order = Order.objects.filter(id=id)
    phone = request.user
    name = request.user.first_name
    created = order[0].created
    now = timezone.now()
    time_d = now - created
    time_m = time_d.total_seconds() // 60
    if time_m < 4320:
        message_user = "کاربر عزیز درخواست شما با موفقیت ارسال شد پشتیبان در اسرع وقت با شما تماس میگیرند"
    else:
        message_user = "زمان ارجاع دادن محصول گذشته است چون بیشتر از ۷۲ ساعت از خرید شما میگذرد"
    message_admin = f'" درخواست داده است. {order[0].id}" جهت ارجاع سفارش با ایدی "{phone}" با شماره تلفن "{name}  ادمین محترم کاربر "'
    send_mail('Refer Product',message_admin, 'mohammad2547mohseny@gmail.com', ['mmhsny429@gmail.com'],
              fail_silently=False)
    context = {
        'order': order[0],
        'phone': phone,
        'name': name,
        'message': message_user

    }
    return render(request, 'refer.html', context)

orders/templates/create_order.html
your prducts:
<ul>
    {% for item in cart %}
    <li>
        product: {{item.quantity}} X {{item.product.name}}

        <p>total price: {{item.total}}</p>
    </li>
    {% endfor %}

</ul>

please enter dataform:
<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit">Enter</button>
</form>

orders/templates/order_detail.html
{% load static tailwind_tags %}
{% load template_tag%}
{% load static %}
<!DOCTYPE html>
<html lang="fa"  dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>جزئیات سفارش</title>
    {% tailwind_css %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-gray-100 text-gray-900">
<div class="container mx-auto p-6">
    <header class="bg-blue-600 p-4 text-white text-center rounded-md mb-6">
        <h1 class="text-3xl font-bold">جزئیات سفارش</h1>
    </header>

    <section class="bg-white rounded-lg shadow-md p-6 mb-4">
        <h2 class="text-2xl font-semibold mb-4">جزئیات سفارش</h2>

        <div class="mb-2">
            <span class="font-bold">تاریخ سفارش   :  {{order.created}}   </span>
        </div>
        <div class="mb-2">
            <span class="font-bold">وضعیت سفارش   :  {{status}}  </span>
        </div>

        {% if order.paid == True %}
        <div class="mb-2">
            <span class="font-bold">استان  :  {{order.province}}</span>
        </div>
        <div class="mb-2">
            <span class="font-bold">شهر  :  {{order.city}}</span>
        </div>
        <div class="mb-2">
            <span class="font-bold">وضعیت پرداخت:پرداخت شده</span>
        </div>
        <div class="mb-2">
            <span class="font-bold">  شماره سفارش:</span>
        </div>
        {% else %}
         <div class="mb-2">
            <span class="font-bold ">پرداخت نشده :وضعیت پرداخت  </span>
        </div>
        {%endif%}
    </section>

    <section class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-2xl font-semibold mb-4">محصولات</h2>
        {% for item in order.items.all %}
        <div class="border-b border-gray-200 pb-4 mb-4">
            <div class="flex justify-between mb-2">
                <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}">{{item.product.description}}</a>
                <span>تعداد:{{item.quantity}}</span>

            </div>
            <div class="flex">
                <span class="pl-4">  قیمت: </span>
                <span><span class="text-emerald-400">  {{item.product.off}}تخفیف   </span>      {{item.product.price}} تومان </span>


            </div>
             {% if order.paid == True %}

                 <a class="hover:text-red-600" href="{% url 'orders:reference' order.id %}">میخواهم این محصول را ارجاع بدهم</a>
            {%endif%}
        </div>
        {% endfor %}


        <div class="flex justify-between font-bold border-t border-gray-200 pt-4">
            <span>مجموع  : {{order.get_final_cost}}تومان</span>

             <a href="{% url 'orders:pdf' order.id %}">download pdf</a>
        </div>
    </section>
</div>

</body>

</html>

orders/templates/order_detail_pdf.html
{% load static tailwind_tags %}
{% load template_tag%}
{% load static %}
<!DOCTYPE html>

<html lang="fa">
<head>
    <link href="https://fonts.googleapis.com/css?family=Vazir" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>order detail</title>
    {% tailwind_css %}
    <style>
        body {
            font-family: 'Vazir', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .order-details {
            max-width: 600px;
            margin: auto;
            background: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s;
        }
        .order-details:hover {
            box-shadow: 0 8px 40px rgba(0, 0, 0, 0.2);
        }
        h1 {
            text-align: center;
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        .detail {
            margin: 10px 0;
            display: flex;
            justify-content: space-between;
            padding: 10px;
            border-bottom: 1px solid #e0e0e0;
        }
        .label {
            font-weight: bold;
            color: #555;
        }
        .value {
            color: #333;
        }
        .total {
            font-size: 18px;
            font-weight: bold;
            color: #d9534f;
            border-top: 2px solid #e0e0e0;
            padding-top: 10px;
            margin-top: 20px;
        }
        footer {
            text-align: center;
            margin-top: 20px;
            color: #777;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="order-details">
        <h1> order detail</h1>
        <div class="detail">
            <span class="label">buyer:</span>
            <span class="value">{{order.buyer}}</span>
        </div>
        <br>
        <div class="detail">
            <span class="label">name:</span>
            <span class="value">{{order.first_name}}</span>
        </div>
        <br>

        {% for item in order.items.all %}
        <div class="detail">
            <span class="label">product:</span>
            <span class="value"> {{item.product.description}}</span>
        </div>
        <br>

        <div class="detail">
            <span class="label">quantity:</span>
            <span class="value">{{item.quantity}}</span>
        </div>
        <br>

        <div class="detail">
            <span class="label">price:</span>
            <span class="value">{{item.product.price}}</span>
        </div>
        <hr>
        {%endfor%}
        <div class="total text-red-100">
            <span class="label">total cost:</span>
            <span class="value">{{order.get_final_cost}}</span>
        </div>
    </div>
</body>
</html>

orders/templates/order_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>Tracking</h2>

<table>
  <tr>
    <th>id(Click for additional information)</th>
    <th>created</th>
    <th>paid</th>
    <th>buyer</th>
  </tr>
  <tr>
      {% for item in order %}

    <td><a href="{% url 'orders:order_detail' item.id %}">{{item.id}}</a></td>
    <td>{{item.created}}</td>
    <td>{{item.paid}}</td>
    <td>{{item.buyer}}</td>
  </tr>
  {%endfor%}

</table>

</body>
</html>

orders/templates/payment-tracking.html
<title>Transaction</title>
    {% if success == True%}
        Your transaction has been successfully completed.
        <br>
        Tracking number: {{RefID}}
        <br>
        Order number: {{order_id}}
        <br>
        <a href="{% url 'shop:product_list'%}">Return to products</a>
    {%else%}
        The transaction was not completed
        <br>
        <a href="{% url 'shop:product_list'%}">Return to products</a>
    {%endif%}

orders/templates/refer.html
{% load static tailwind_tags %}
{% load template_tag%}
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>صفحه محصول</title>
    {% tailwind_css %}
</head>
<body class="bg-gray-100">

    <div class="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow-md mt-10">
        <h1 class="text-2xl font-bold text-gray-800 mb-4">{{product}}</h1>
        {% for img in product.images.all %}
        <img src="{{img.file.url}}" alt="تصویر محصول" class="w-full h-full object-cover rounded-lg mb-4">
        {% endfor %}
        <p class="text-gray-700 mb-4">{{message}}</p>


        <div class="flex justify-between mt-6">

            <a href="{% url 'shop:product_list'%}" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">بازگشت به لیست محصولات</a>
        </div>
    </div>

</body>
</html>

orders/templates/verify-code.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">ارسال کد تایید</button>
</form>
<p>thank </p>

orders/templates/verify_code.html
<!DOCTYPE html>
<html lang="fa">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        #countdown {
            font-size: 20px;
            color: #333;
            border-style: solid;
            width:100px;
            height:30px;
            justify-content:center;

        }
    </style>
</head>
<body>
    <div id="countdown">02:00</div>

    <script>
        let time = 120;
        const countdownElement = document.getElementById('countdown');

        const countdownInterval = setInterval(() => {
            const minutes = Math.floor(time / 60);
            const seconds = time % 60;
            const formattedTime = String(minutes).padStart(2, '0') + ":" + String(seconds).padStart(2, '0');
            countdownElement.textContent = formattedTime;
            time--;
            if (time < 0) {
                clearInterval(countdownInterval);
                countdownElement.textContent = "Time is up";
            }
        }, 1000);
    </script>
    {% for message in messages%}
         {{message}}
    {% endfor %}
    <form method="post">
        {% csrf_token %}
         <input type="text" placeholder="enter code" name="code">
        <button type="submit">تایید کد </button>
    </form>
</body>
</html>

orders/templates/verify_phone.html
{% for message in messages%}
    {{message}}
{% endfor %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">ارسال کد تایید</button>
</form>