Shopweb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/",include('account.urls',namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove_item/', views.remove_item, name='remove_item'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('verify-code/', views.verify_code, name='verify_code'),
    path('create-order/', views.create_order, name='create_order'),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_details/<int:id>', views.order_detail, name='order_detail'),
    path('pdf/<int:id>>', views.send_to_pdf, name='pdf'),
    path('reference/<int:id>', views.reference, name='reference'),
    path('apply-discount/',views.apply_discount, name='apply_discount'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [

    path('product/', views.product_list, name='product_list'),
    path('product/<slug:category_slug>', views.product_list, name='product_by_category'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('product/save/<int:id>', views.save, name='save'),
    path('product/save_list/', views.save_list, name='save_list')
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from shop.models import Product
from .cart import Cart
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from kavenegar import *

# Create your views here.


@require_POST
def add_to_cart(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product)
        cart.save()
        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
        }
        return JsonResponse(context)
    except:
        return JsonResponse({"error": "Invalid request."})


def cart_detail(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/detail.html', context)


@require_POST
def update_quantity(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        if action == 'add':
            cart.add(product)
        elif action == 'decrease':
            cart.decrease(product)

        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
            'quantity': cart.cart[item_id]['quantity'],
            # 'price': cart.cart[item_id]['price'],
            'total': cart.cart[item_id]['quantity'] * cart.cart[item_id]['price'],
            'final_price': cart.get_final_price(),
            'success': True,
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, 'error': 'Item not found!'})


@require_POST
def remove_item(request):
    item_id = request.POST.get('item_id')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        cart.remove(product)
        context = {
            'item_count': len(cart),
            'final_price': cart.get_final_price(),
            'total_price': cart.get_total_price(),
            'success': True,
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, "error": 'Item not found'}, status=status.HTTP_400_NOT_FOUND)

cart/templates/cart/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}cart{% endblock %}

{% block content %}
<div class="header">
    <h1> سبد خرید</h1>
</div>
<div class="cart-detail-container">

    {% for item in cart %}

    <div class="product-item" data-item-id="{{ item.product.id }}">

        <img src="{{ item.product.images.first.file.url }}" class="product-image">

        <div class="product-info">
            <h3>

                نام محصول : {{ item.product.name }}

            </h3>
            <p>تعداد: <span id="item-quantity-{{ item.product.id }}">{{ item.quantity }}</span></p>
            <p>قیمت هر محصول: <span>{{ item.price }}</span></p>
            <p>قیمت کل: <span id="item-total-{{ item.product.id }}">{{ product_price }}</span></p>
        </div>
        <div class="actions">
            <div class="quantity-add">+</div>
            <div class="quantity-decrease" id="">-</div>
            <div class="quantity-remove">حذف</div>
        </div>
    </div>

    {% endfor %}
    {% if cart%}
        <div class="total-price">
            <p>قیمت کل:<span id="item-total_price">{{ cart.get_total_price }}</span>تومان </p>
            <p>هزینه ارسال:<span id="item-post_price">{{ cart.get_post_price}}</span>تومان </p>
            <p>مبلغ قابل پرداخت:<span id="item-final_price">{{ cart.get_final_price}}</span>تومان </p>
        </div>
    {% endif %}
    <div class="checkout-buttons">
        <div class="continue-btn"><a href="{% url 'orders:verify_phone' %}">ادامه خرید</a></div>
        <div class="back-btn"><a href="{% url 'shop:product_list' %}">برگشت به لیست محصولات</a></div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function(){

        $('.quantity-add').on('click', function(){
            updateQuantity($(this).closest('.product-item').data('item-id'), 'add');
        });

        $('.quantity-decrease').on('click', function(){
            updateQuantity($(this).closest('.product-item').data('item-id'), 'decrease');
        });

        $('.quantity-remove').on('click', function(){
            removeItem($(this).closest('.product-item').data('item-id'));
        });

        function updateQuantity(itemId, action){
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:update_quantity' %}',
                data: {
                    'item_id': itemId,
                    'action': action,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response){
                    if (response.success) {
                        $('#item_count').text(response.item_count);
                        $('#total_price').text(response.total_price);
                        $('#item-quantity-'+ itemId).text(response.quantity);
                        $('#item-total-'+ itemId).text(response.total + ' '+ 'تومان');
                        $('#item-total_price').text(response.total_price + ' ');
                        $('#item-final_price').text(response.final_price + ' '+ 'تومان');
                    } else {
                        alert('Error updating quantity!');
                    }
                }

            });
        }

        function removeItem(itemId){
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:remove_item' %}',
                data: {
                    'item_id': itemId,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response){
                    if (response.success) {
                        $('#item_count').text(response.item_count);
                        $('#total_price').text(response.total_price);
                        $('#item-total_price').text(response.total_price);
                        $('#item-final_price').text(response.final_price);
                        $(`.product-item[data-item-id=${itemId}]`).remove();
                    } else {
                        alert('Error updating quantity!');
                    }
                }

            });
        }

    });

</script>
{% endblock %}