Shopweb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/",include('account.urls',namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('logout',views.log_out,name='logout')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove_item/', views.remove_item, name='remove_item'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('verify-code/', views.verify_code, name='verify_code'),
    path('create-order/', views.create_order, name='create_order'),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_details/<int:id>', views.order_detail, name='order_detail'),
    path('pdf/<int:id>>', views.send_to_pdf, name='pdf'),
    path('reference/<int:id>', views.reference, name='reference'),
    path('apply-discount/',views.apply_discount, name='apply_discount'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [

    path('product/', views.product_list, name='product_list'),
    path('product/<slug:category_slug>', views.product_list, name='product_by_category'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('product/save/<int:id>', views.save, name='save'),
    path('product/save_list/', views.save_list, name='save_list')
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
from account.models import ShopUser


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(max_length=1200)
    inventory = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)
    weight = models.PositiveIntegerField(default=0)
    off = models.PositiveIntegerField(default=0)
    new_price = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def percent(self):
        return round((self.off / self.price) * 100)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    file = models.ImageField(upload_to="product_images/%Y/%m/%d")
    title = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]


class ProductFeature(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, related_name='features', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ":" + self.value


class ProductSave(models.Model):
    user = models.ForeignKey(ShopUser, related_name='user_save', on_delete=models.CASCADE)
    products = models.ForeignKey(Product,related_name='products_save', on_delete=models.CASCADE,default=None)

shop/views.py
from django.shortcuts import render, redirect
from .models import *
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse


# Create your views here.


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    print(category)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        products = paginator.page(1)
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, slug=slug, id=id)
    category = product.category
    # request.session.delete()
    context = {
        'product': product,
        'category': category,
    }
    return render(request, 'shop/detail.html', context)


def save(request, id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)
        save_p = ProductSave.objects.all()
        p = []
        for i in save_p:
            name = str(i.products)
            p += [name]
        if str(product) not in p:
            save_product = ProductSave.objects.create(user=request.user, products=product)
            save_product.save()
            return HttpResponse('با موفقیت ذخیره شد')
        else:
            return HttpResponse('شما قبلا این محصول به فهرست علاقه مندیتان اضافه کرده اید.')


def save_list(request):
    if request.user.is_authenticated:
        save = ProductSave.objects.all()
        return render(request, 'shop/save.html', {'save': save})

shop/templates/partials/header.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>فروشگاه</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css">
    <style>
        .count-badge {
            position: absolute;

            right: 70px;
            background-color: gray;
            color: white;
            border-radius: 9999px;
            padding: 0.2em 0.6em;
            font-size: 0.75rem;
        }
    </style>
</head>
<body>
  {% with item_count=cart|length %}
    <header class="bg-gray-100 shadow items-center justify-between flex">
        <div class="container mx-auto flex justify-between items-center p-4 relative">
            <h1 class="text-lg font-bold">فروشگاه</h1>


                 {% if request.user.is_authenticated%}
                    <a href="{% url 'orders:order_list'%}" class="text-gray-600 hover:text-blue-600 transition duration-200">لیست سفارشات</a>
                    <a href="{% url 'accounts:logout'%}" class="text-gray-600 hover:text-blue-600 transition duration-200">خروج از حساب کاربری</a>
                    <a href="{% url 'shop:save_list'%}" class="text-gray-600 hover:text-blue-600 transition duration-200">لیست علاقه مندی</a>
                {%endif%}
                <a id="cartIcon" href="{% url 'cart:cart_detail'%}" class="relative text-gray-600 hover:text-blue-600 transition duration-200">

                    <span class="count-badge " id="item_count">{{item.count}}</span>
                    <span class="ml-1">سبد خرید</span>
                </a>

        </div>
    </header>
   {% endwith %}

</body>
</html>

shop/templates/partials/pagination.html
<div class="pagination">
{% if page.has_previous %}
    <a class="page-a" href="?page={{ page.previous_page_number }}"><span class="point" >«</span></a>
  {% if page.number > 3 %}
    <a class="page-a square" href="?page=1">1</a>
    {% if page.number > 4 %}
      <span class="page-a point">...</span>
    {% endif %}
  {% endif %}
{% endif %}

{% for num in page.paginator.page_range %}
  {% if page.number == num %}
    <a class="page-a square-red" href="?page={{ num }}">{{ num }}</a>
  {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
    <a class="page-a square" href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}

{% if page.has_next %}
  {% if page.number < page.paginator.num_pages|add:'-3' %}
    <span class="page-a point">...</span>
    <a class="page-a square" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a>
  {% elif page.number < page.paginator.num_pages|add:'-2' %}
    <a class="page-a square" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a>
  {% endif %}

    <a class="page-a" href="?page={{ page.next_page_number }}"><span class="point" >»</span></a>
{% endif %}
</div>