Shopweb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/",include('account.urls',namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove_item/', views.remove_item, name='remove_item'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [

    path('product/', views.product_list, name='product_list'),
    path('product/<slug:category_slug>', views.product_list, name='product_by_category'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('product/save/<int:id>', views.save, name='save'),
    path('product/save_list/', views.save_list, name='save_list')
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
from account.models import ShopUser


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(max_length=1200)
    inventory = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)
    weight = models.PositiveIntegerField(default=0)
    off = models.PositiveIntegerField(default=0)
    new_price = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def percent(self):
        return round((self.off / self.price) * 100)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    file = models.ImageField(upload_to="product_images/%Y/%m/%d")
    title = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]


class ProductFeature(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, related_name='features', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ":" + self.value


class ProductSave(models.Model):
    user = models.ForeignKey(ShopUser, related_name='user_save', on_delete=models.CASCADE)
    products = models.ForeignKey(Product,related_name='products_save', on_delete=models.CASCADE,default=None)

shop/views.py
from django.shortcuts import render, redirect
from .models import *
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse


# Create your views here.


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    print(category)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        products = paginator.page(1)
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, slug=slug, id=id)
    category = product.category
    # request.session.delete()
    context = {
        'product': product,
        'category': category,
    }
    return render(request, 'shop/detail.html', context)


def save(request, id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)
        save_p = ProductSave.objects.all()
        p = []
        for i in save_p:
            name = str(i.products)
            p += [name]
        if str(product) not in p:
            save_product = ProductSave.objects.create(user=request.user, products=product)
            save_product.save()
            return HttpResponse('با موفقیت ذخیره شد')
        else:
            return HttpResponse('شما قبلا این محصول به فهرست علاقه مندیتان اضافه کرده اید.')


def save_list(request):
    if request.user.is_authenticated:
        save = ProductSave.objects.all()
        return render(request, 'shop/save.html', {'save': save})

shop/templates/shop/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load template_tag%}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%}order detail{%endblock%}
    {% tailwind_css %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
{% block content %}
<body class="bg-gray-100">
    <div class="container w-full p-6">
        <div class="bg-white rounded-md shadow-md p-6 mb-6 w-full">
            <h1 class="text-2xl font-bold mb-4">نام محصول:{{product.name}}</h1>
            <img src="{{product.images.first.file.url}}" alt="نام محصول" class=" object-cover mb-4 rounded-md">

            <div class="flex justify-between items-center mb-4">
                <span class="text-lg font-semibold">دسته بندی: <span class="text-gray-600">{{product.category}}</span></span>
                <span class="text-lg font-semibold text-red-500">قیمت: {{product.price}} تومان</span>
            </div>
            {% if product.off %}
            <div class="mb-4">
                <span class="text-lg font-semibold text-green-500">قیمت پس از تخفیف: {{ product.new_price}} تومان</span>
            </div>
            {%endif%}

            <button class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" type="button" id="add-cart">اضافه به سبد خرید</button>

            <a href="{% url 'shop:save' product.id %}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">افزودن به علاقه مندی ها</a>

            <hr class="my-4">

            <h2 class="text-lg font-semibold mb-2">توضیحات محصول:</h2>
            <p class="text-gray-700 mb-4">{{ product.description }}</p>
        </div>
</div>
    <h2 class="text-xl font-bold m-4">محصولات مرتبط</h2>
        <div class="bg-white rounded-md shadow-md p-6 flex gird-cols-4 gap-6">

            {% suggestions product.category product.id as products %}
            {% for i in products %}
            <div class="grid  flex items-cetner gap-6">


                <div class="bg-gray-200 p-4 rounded-md">
                    <h3 class="font-semibold">محصول: {{i.name}}</h3>

                    <img src="{{ i.images.first.file.url }}" alt="{{i.name}}" class=" object-cover mb-2 rounded-md">
                    <p class="text-lg font-semibold text-red-500 m-4">
                       قیمت: {{i.price}} تومان</p>
                    <a class="bg-blue-500 text-white mt-2 px-4 py-1 rounded-md hover:bg-blue-600" href="{{i.get_absolute_url}}">جزئیات بیشتر</a>
                </div>
            </div>
            {% endfor%}

        </div>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('#add-cart').click(function(){
                var button = $(this);
                $.ajax({
                   type: 'POST',
                   url: '{% url 'cart:add_to_cart' product.id %}',
                   data:{'csrfmiddlewaretoken':'{{ csrf_token }}'},
                   success: function(data) {
                    $('#item_count').text(data.item_count);
                    $('#total_price').text(data.total_price);

                   },
                });
            });
        });
    </script>
</body>
</html>
{% endblock %}

shop/templates/shop/list.html
{% extends 'parent/base.html' %}
{% load static tailwind_tags %}
{% load static %}
{% block title %}product list{% endblock %}
{% block content %}
{% load template_tag%}
    <head dir="rtl">
        {% tailwind_css %}
        <svg class="hidden">
            <symbol id="curve" width="100" height="22" viewBox="0 0 100 22" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M50 0C69 0 81 22 100 22L0 22C18.75 22 31 0 50 0Z"/>
            </symbol>
            <symbol id="chevron-down" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
            </symbol>
            <symbol id="curve" width="100" height="22" viewBox="0 0 100 22" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                 <path d="M50 0C69 0 81 22 100 22L0 22C18.75 22 31 0 50 0Z"/>
            </symbol>
            <symbol id="chevron-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" >
                <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
            </symbol>
             <symbol id="arrow-right-left" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 21 3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" />
            </symbol>
            <symbol id="star" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
              <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z" />
            </symbol>
            <symbol id="shopping-cart" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
            </symbol>
            <symbol id="star-solid" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
              <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />
            </symbol>
            <symbol id="chevron-right-mini" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
              <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
            </symbol>
            <symbol id="chevron-left-mini" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
            </symbol>
        </svg>
    </head>
<!--header-->
<div class="header fix">
    {% if category %}
        <h3>List of products by category {{ category.name }}</h3>
    {% else %}
        <h1> list product</h1>
    {% endif %}
</div>
<div class="flex justify-evenly items-first">
<!--    list div-->
    <div class="flex flex-col items-center gap-x-5">
        <div class="" >
            <div class="grid grid-cols-4 gap-x-1">
        {%for i in products%}
            <div class="w-[300px]">
                <div class="child:rounded-2xl child:bg-white child:shadow-normal m-3 w-[300px] ">
                    <a href="{% url 'shop:product_detail' i.id i.slug %}">
                        <div class="dark:bg-zinc-700 justify-between p-2 m-4 relative  w-[255px] h-[472px] ">
                            <div class="p-5  pt-8 mb-5">
                                <img src="{{ i.images.first.file.url }} " class=" h-[250px] w-[250px] mx-auto my-auto items-center" loading="lazy">
                            </div>
                            {% if  i.off and i.inventory %}
                            <span class="absolute top-1.5 right-1.5 rounded-full  block h-[30px] leading-[30px] bg-orange-300 text-white dark:text-zinc-700 px-3.5">{{i.percent}}%</span>
                            {% endif %}
                            <h5 class="font-dana-medium text-xl h-14 text-zinc-700 dark:text-white line-clamp-2"> {{ i.name }}</h5>
                    </a>
            {% if not i.inventory %}
                <div>
                    <span class="text-red-400  text-xl pt-3">موجود نیست</span>
                </div>
            {% else %}
            <div class="mt-2.5 flex gap-x-2.5">
                <div class="text-teal-600 dark:text-emerald-500 ">
                    <span class="font-dana-demibold text-xl"> {{ i.new_price }}</span>
                    <span class="text-sm tracking-tighter ">تومان</span>
                </div>
                {% if i.off %}
                    <div class="offer  text-gray-400">
                        <span class="font-dana-regular text-xl"> {{ i.price }}</span>
                        <span class="text-sm tracking-tighter ">تومان</span>
                    </div>
                {% endif %}
            </div>
        {% endif %}
            <div class=" flex items-center  justify-between mt-2.5">
                <div class="flex gap-x-3 ">
                    <a href="{% url 'cart:add_to_cart' i.id %}">
                    <span class="text-gray-400 dark:bg-zinc-800 hover:bg-teal-600 cursor-pointer dark:hover:bg-emerald-500 transition-all hover:text-white rounded-full flex items-center justify-center w-fit">
                        <svg class="h-[30px] w-[28px]  p-1 ">
                            <use href="#shopping-cart"></use>
                        </svg>
                    </span>
                    </a>
                    <span class="text-gray-400 cursor-pointer dark:hover:text-emerald-500 transition-all hover:text-teal-600    rounded-full flex items-center justify-center w-fit">
                        <svg class="h-[30px] w-[28px]  p-1 ">
                            <use href="#arrow-right-left"></use>
                        </svg>
                    </span>
                </div>
                <div class="flex text-yellow-500  ">
                    <svg class="w-6 h-6 h text-gray-300 dark:text-gray-400 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                </div>
            </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    </div>
<!--    expensive product-->
    <h1 class="text-lg">order by expensive product: </h1>
    <div class="grid grid-cols-4">
    {% most_expensive as ep %}
    {% for i in ep %}
        {% if i.inventory%}
            <div class="flex flex-nowrap">
                <div class="child:rounded-2xl child:bg-white child:shadow-normal m-3  flex">
                    <a href="{% url 'shop:product_detail' i.id i.slug %}">
                        <div class="dark:bg-zinc-700 justify-between p-2 relative m-auto w-[255px] h-[472px] ">
                            <div class="p-5  pt-8 mb-5">
                                <img src="{{ i.images.first.file.url }} " class=" h-[255px] w-[250px] mx-auto my-auto items-center" loading="lazy">
                        </div>
                        {% if  i.off and i.inventory %}
                            <span class="absolute top-1.5 right-1.5 rounded-full  block h-[30px] leading-[30px] bg-orange-300 text-white dark:text-zinc-700 px-3.5">{{i.percent}}%</span>
                        {% endif %}
                         <h5 class="font-dana-medium text-xl h-14 text-zinc-700 dark:text-white line-clamp-2"> {{ i.name }}</h5>
                        {% if i.inventory %}
                        <div class="mt-2.5 flex gap-x-2.5">
                             <div class="text-teal-600 dark:text-emerald-500 ">
                                <span class="font-dana-demibold text-xl"> {{ i.new_price }}</span>
                                <span class="text-sm tracking-tighter ">تومان</span>
                             </div>
                            {% if i.off %}
                              <div class="offer  text-gray-400">
                                 <span class="font-dana-regular text-xl"> {{ i.price }}</span>
                                 <span class="text-sm tracking-tighter ">تومان</span>
                             </div>
                            {% endif %}
                         </div>
                {% endif %}
            <div class=" flex items-center  justify-between mt-2.5">
                <div class="flex gap-x-3 ">
                    <a href="{% url 'cart:add_to_cart' i.id %}">
                    <span class="text-gray-400 dark:bg-zinc-800 hover:bg-teal-600 cursor-pointer dark:hover:bg-emerald-500 transition-all hover:text-white rounded-full flex items-center justify-center w-fit">
                        <svg class="h-[30px] w-[28px]  p-1 ">
                            <use href="#shopping-cart"></use>
                        </svg>
                    </span>
                    </a>
                    <span class="text-gray-400 cursor-pointer dark:hover:text-emerald-500 transition-all hover:text-teal-600    rounded-full flex items-center justify-center w-fit">
                        <svg class="h-[30px] w-[28px]  p-1 ">
                            <use href="#arrow-right-left"></use>
                        </svg>
                    </span>
                </div>
                <div class="flex text-yellow-500  ">
                    <svg class="w-6 h-6 h text-gray-300 dark:text-gray-400 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                    <svg class="w-6 h-6 ">
                        <use href="#star"></use>
                    </svg>
                </div>
            </div>
                </div>
            </div>
        </div>
        {%endif%}
    {% endfor %}
    </div>
    <div class="text-center justify-between">
            {% include 'partials/pagination.html' with page=products %}
    </div>
</div>
    <div class="w-[300px] h-[500px] ">
            <div class="bg-slate-500 p-3 border-2 w-[300px] h-[500px] relative " >
          <a href="{% url 'shop:product_list' %}" class="text-lg">همه</a>

        {% for ct in categories %}
        <br>
        <div class="py-3 text-stone-800">
            <a href="{{ ct.get_absolute_url }}" class="text-neutral-800 text-lg font-bold"><li>{{ ct.name }}</li></a>
        </div>
        {% endfor %}       <hr>
        <span>فیلتر</span>
        <div class="">
            <span class="m-3 text-lg">برند</span>
            <select id="car" onchange="ChangeCarList()">
             <option value="">پوشاک</option>
             <option value="VO">اریان نخ</option>
             <option value="VW">رایسی</option>
             <option value="BMW">ری بن</option>
            </select>
            <br>
            <br>
            <hr>
            <br>
            <span class="m-3 text-lg">محدوده قیمت</span>
            <select id="car۱" onchange="ChangeCarList()">
             <option value="">گرانترین</option>
             <option value="VO"> ارزانترین</option>
            </select>
        </div>
    </div>
    </div>
{% endblock %}

shop/templates/shop/login.html
{% if user.is_authenticated %}
    <p>You are login</p>
    <a href="{% url 'shop:product_list'%}">Return to product list</a>
    <a href="{%%}">Log out</a>
{%else%}
    <p>you are not login</p>
{%endif%}

shop/templates/shop/save.html
{% load static %}
{% load template_tag%}
{% load static tailwind_tags %}
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>جزئیات محصول</title>
    {% tailwind_css %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 ">
    <h2 class="text-xl font-bold m-4"> علاقه مندی ها</h2>
        <div class="bg-white rounded-md shadow-md p-6 grid h-auto grid-cols-4 gap-6">


            {% for i in save %}



                <div class="bg-gray-200 p-4 rounded-md h-auto relative h-[600px]">
                    <h3 class="font-semibold m-4">محصول: {{i.products}}</h3>

                    <img src="{{ i.products.images.first.file.url }}" alt="{{i.name}}" class=" object-cover mb-2 rounded-md">
                    <div class="flex justify-between items-center relative">
                         <a class="absolute bg-blue-500 text-white mt-2 px-4 py-1 rounded-md hover:bg-blue-600 bottom-2" href="{{i.products.get_absolute_url}}">جزئیات بیشتر</a>
                        <span class="absolute text-lg font-semibold text-red-500 m-4 left-0">قیمت: {{i.products.price}} تومان</span>
                    </div>
                </div>


            {%endfor%}
        </div>
</body>